export type StageStatus = "PENDING" | "RUNNING" | "READY" | "FAILED" | "FAILED_OOM" | "INVALIDATED" | "CANCELLED";
export type ViewName = "front" | "left" | "back" | "right";
export interface ReferenceSlot { view: ViewName; required: boolean; original_path?: string; processed_path?: string; quality?: { level: "GOOD" | "WARNING" | "ERROR"; warnings: string[]; errors: string[]; foreground_ratio: number; [key: string]: unknown }; }
export interface StageRecord { name: string; status: StageStatus; finished_at?: string | null; started_at?: string | null; log_path?: string; error_category?: string; error_message?: string; result: Record<string, unknown>; }
export interface Job { job_id: string; status: string; profile: "SAFE" | "BALANCED" | "MAX" | "CUSTOM"; resolution: number; references: Record<string, ReferenceSlot>; stages: Record<string, StageRecord>; equipment_assets: string[]; motion_clips: string[]; export_actions: string[]; warnings: string[]; requested_provider?: "AUTO" | "Spar3DProvider" | "HunyuanMultiviewProvider" | "HunyuanSingleViewProvider"; actual_provider?: string; fallback_reason?: string | null; inference_steps: number; octree_resolution: number; geometry_num_chunks: number; low_vram_mode: boolean; texture_resolution: 512 | 1024 | 2048; updated_at: string; }
export interface Job { clothing_assets: string[]; }
export interface Job { retopology_mode: "KEEP_SOURCE" | "TRIANGLE" | "QUAD"; retopology_target_faces: number; }
export interface MotionClip { id: string; name: string; category?: string; duration?: number; loop?: boolean; rootMotion?: boolean; license?: string; allowed_for_commercial_use?: boolean; }
export interface MotionCatalog { schema_version: number; libraries: Array<{ id: string; name?: string; license?: string; allowed_for_commercial_use?: boolean; clips?: MotionClip[] }>; available_clips: MotionClip[]; recommended_clips?: string[]; }
export interface EquipmentAsset { id: string; name: string; asset_type: string; slot: string; handedness?: string | null; primary_socket?: string | null; tags?: string[]; validation?: { valid: boolean; vertex_count?: number; face_count?: number; material_count?: number; texture_count?: number }; }
export interface EquipmentCatalog { schema_version: number; assets: EquipmentAsset[]; }
export interface Hardware { os: Record<string, unknown>; cpu: Record<string, unknown>; ram: { total_gb: number }; gpu: { available: boolean; gpus: Array<{ name: string; vram_mb: number; used_vram_mb?: number; driver: string; compute_capability: string }>; }; cuda: Record<string, unknown>; blender: { available: boolean; path?: string }; recommendation: string; disk: { free_gb: number }; }
export interface Capabilities { providers: Record<string, { available: boolean; reason?: string }>; stages: Record<string, { available: boolean; description?: string; reason?: string }>; }
export interface CacheItem { job_id: string; status: string; cache_bytes: number; protected_bytes: number; cleanable: boolean; reason: string; }
export interface AcceptanceReport { job_id: string; valid: boolean; checks: Array<{ id: string; label: string; passed: boolean; detail: string }>; metrics: { vertices: number; textures: number; bones: number; animations: number; selected_actions: number }; }
async function request<T>(url: string, init?: RequestInit): Promise<T> { const response = await fetch(url, init); if (!response.ok) throw new Error((await response.json().catch(() => null))?.detail ?? `${response.status} ${response.statusText}`); return response.json() as Promise<T>; }
export const api = {
  hardware: () => request<Hardware>("/api/hardware"), capabilities: () => request<Capabilities>("/api/capabilities"), jobs: () => request<Job[]>("/api/jobs"), motions: () => request<MotionCatalog>("/api/motions"), equipment: () => request<EquipmentCatalog>("/api/equipment"), cache: () => request<{ items: CacheItem[] }>("/api/cache"), cleanCache: (jobIds: string[]) => request<{ cleaned: Array<{ job_id: string; deleted_bytes: number }>; skipped: Array<{ job_id: string; reason: string }>; deleted_bytes: number }>("/api/cache/clean", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ job_ids: jobIds }) }),
  createJob: (body: { name: string; profile: string; resolution: number; requested_provider: string }) => request<Job>("/api/jobs", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(body) }),
  upload: (jobId: string, view: ViewName, file: File) => { const form = new FormData(); form.append("file", file); return request<Job>(`/api/jobs/${jobId}/references/${view}`, { method: "POST", body: form }); },
  runStage: (jobId: string, stage: string) => request<{ status: string }>(`/api/jobs/${jobId}/stages/${stage}/run`, { method: "POST" }),
  build: (jobId: string) => request<{ status: string; job_id: string }>(`/api/jobs/${jobId}/build`, { method: "POST" }),
  cancelBuild: (jobId: string) => request<{ cancelled: boolean }>(`/api/jobs/${jobId}/build/cancel`, { method: "POST" }),
  cancelStage: (jobId: string, stage: string) => request<{ cancelled: boolean }>(`/api/jobs/${jobId}/stages/${stage}/cancel`, { method: "POST" }),
  setExportSelection: (jobId: string, actions: string[]) => request<Job>(`/api/jobs/${jobId}/export-selection`, { method: "PUT", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ actions }) }),
  setMotionSelection: (jobId: string, clips: string[]) => request<Job>(`/api/jobs/${jobId}/motion-selection`, { method: "PUT", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ clips }) }),
  setEquipmentSelection: (jobId: string, assets: string[]) => request<Job>(`/api/jobs/${jobId}/equipment-selection`, { method: "PUT", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ assets }) }),
  setClothingSelection: (jobId: string, assets: string[]) => request<Job>(`/api/jobs/${jobId}/clothing-selection`, { method: "PUT", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ assets }) }),
  setRetopologySettings: (jobId: string, mode: Job["retopology_mode"], targetFaces: number) => request<Job>(`/api/jobs/${jobId}/retopology-settings`, { method: "PUT", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ mode, target_faces: targetFaces }) }),
  setJobSettings: (jobId: string, settings: Pick<Job, "profile" | "resolution" | "requested_provider" | "inference_steps" | "octree_resolution" | "geometry_num_chunks" | "low_vram_mode" | "texture_resolution">) => request<Job>(`/api/jobs/${jobId}/settings`, { method: "PUT", headers: { "Content-Type": "application/json" }, body: JSON.stringify(settings) }),
  acceptance: (jobId: string, full = false) => request<AcceptanceReport>(`/api/jobs/${jobId}/acceptance?full=${full}`, { method: "GET" }),
  evaluateAnimationGraph: (jobId: string, input: { speed: number; direction_degrees: number; grounded: boolean; crouched: boolean; sprinting: boolean; equipment_type?: string | null; action?: string | null; action_time: number; combo_index: number; previous_state?: string | null; delta_time?: number; root_motion_enabled?: boolean; upper_body_action?: string | null; emote?: string | null; vertical_velocity?: number; transition_duration?: number | null }) => request<{ state: string; clip_id: string | null; action_name: string | null; blend: number; normalized_time: number; root_motion: boolean; reason: string; direction_degrees: number; transition?: string | null; transition_duration: number; root_motion_mode: string; layers: Array<{ name: string; clip_id?: string; blend_tree?: Array<{ clip_id: string; action_name: string; weight: number }>; weight: number; mask: string }>; blend_tree: Array<{ clip_id: string; action_name: string; weight: number }>; additive_clip_id?: string | null }>(`/api/jobs/${jobId}/animation-graph`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(input) }),
};
