import { useEffect, useMemo, useState } from "react";
import { api, Capabilities, Hardware, Job, ViewName } from "./api";
import Viewport from "./Viewport";

const views: Array<{ id: ViewName; label: string; required: boolean }> = [
  { id: "front", label: "FRONT", required: true }, { id: "left", label: "LEFT", required: false }, { id: "back", label: "BACK", required: false }, { id: "right", label: "RIGHT", required: false },
];

function App() {
  const [hardware, setHardware] = useState<Hardware>(); const [capabilities, setCapabilities] = useState<Capabilities>(); const [jobs, setJobs] = useState<Job[]>([]); const [active, setActive] = useState<Job>(); const [error, setError] = useState(""); const [busy, setBusy] = useState(false);
  const refresh = async () => { try { const [hw, caps, list] = await Promise.all([api.hardware(), api.capabilities(), api.jobs()]); setHardware(hw); setCapabilities(caps); setJobs(list); if (!active && list[0]) setActive(list[0]); } catch (err) { setError(err instanceof Error ? err.message : String(err)); } };
  useEffect(() => { void refresh(); }, []);
  useEffect(() => { if (!active) return; const timer = window.setInterval(() => { void api.jobs().then(list => { setJobs(list); const next = list.find(job => job.job_id === active.job_id); if (next) setActive(next); }); }, 1000); return () => window.clearInterval(timer); }, [active?.job_id]);
  const create = async () => { setBusy(true); setError(""); try { const job = await api.createJob({ name: "Character Unit", profile: hardware?.recommendation ?? "BALANCED", resolution: 512, requested_provider: "AUTO" }); setActive(job); setJobs(list => [job, ...list]); } catch (err) { setError(err instanceof Error ? err.message : String(err)); } finally { setBusy(false); } };
  const upload = async (view: ViewName, file?: File) => { if (!active || !file) return; setBusy(true); try { const job = await api.upload(active.job_id, view, file); setActive(job); setJobs(list => list.map(item => item.job_id === job.job_id ? job : item)); } catch (err) { setError(err instanceof Error ? err.message : String(err)); } finally { setBusy(false); } };
  const runReferences = async () => { if (!active) return; setBusy(true); try { await api.runStage(active.job_id, "references"); } catch (err) { setError(err instanceof Error ? err.message : String(err)); } finally { setBusy(false); } };
  const runStage = async (stage: string) => { if (!active) return; setBusy(true); setError(""); try { await api.runStage(active.job_id, stage); } catch (err) { setError(err instanceof Error ? err.message : String(err)); } finally { setBusy(false); } };
  const activeStage = active?.stages.references; const gpu = hardware?.gpu.gpus[0]; const readyViews = useMemo(() => Object.values(active?.references ?? {}).filter(slot => slot.quality?.level !== "ERROR").length, [active]);
  const assetStage = ["rig", "retopology", "geometry"].map(stage => active?.stages[stage]).find(stage => stage?.status === "READY");
  const assetPath = typeof assetStage?.result.mesh_path === "string" ? assetStage.result.mesh_path : undefined;
  const assetUrl = active && assetPath ? `/api/jobs/${active.job_id}/files/${assetPath.split("/").map(encodeURIComponent).join("/")}` : undefined;
  return <div className="app-shell">
    <header className="topbar"><div className="brand"><div className="brand-mark">CF</div><div><h1>Character Factory</h1><p>Local production pipeline</p></div></div><div className="top-actions"><span className="status-dot" /> LOCAL ONLY <button className="secondary" onClick={() => void refresh()}>Refresh</button></div></header>
    <main className="workspace"><aside className="sidebar"><div className="section-head"><span>UNITS</span><button className="icon-button" onClick={() => void create()} disabled={busy}>＋</button></div>{jobs.length === 0 && <p className="muted">No units yet</p>}{jobs.map(job => <button key={job.job_id} className={`job-row ${active?.job_id === job.job_id ? "selected" : ""}`} onClick={() => setActive(job)}><span className="job-icon">◇</span><span><strong>{job.job_id.slice(0, 8)}</strong><small>{job.status} · {job.profile}</small></span></button>)}<div className="sidebar-bottom"><span>PIPELINE VERSION</span><strong>0.1.0 foundation</strong></div></aside>
      <section className="content"><div className="content-title"><div><div className="eyebrow">WORKSPACE / {active ? active.job_id.slice(0, 8) : "NEW UNIT"}</div><h2>Character pipeline</h2></div><button className="primary" onClick={() => void create()} disabled={busy}>＋ New unit</button></div>{error && <div className="error-banner">{error}</div>}
        {!active ? <div className="welcome"><h3>Start a character unit</h3><p>Create a persistent job to begin with reference intake and diagnostics.</p><button className="primary" onClick={() => void create()}>Create unit</button></div> : <>
          <div className="dashboard-grid"><div className="panel references"><div className="panel-header"><div><span className="eyebrow">01 / INPUT</span><h3>Reference images</h3></div><span className={`pill ${readyViews ? "good" : "neutral"}`}>{readyViews}/4 uploaded</span></div><p className="panel-note">Front is required. Processed images are persisted separately from originals.</p><div className="reference-grid">{views.map(view => { const slot = active.references[view.id]; return <label key={view.id} className={`drop-slot ${slot ? "has-file" : ""}`}><input type="file" accept="image/png,image/jpeg,image/webp" onChange={event => void upload(view.id, event.target.files?.[0])} /><span className="slot-label">{view.label}{view.required && <sup>*</sup>}</span>{slot ? <><span className="slot-check">✓</span><small>{slot.quality?.level ?? "uploaded"}</small></> : <span className="upload-hint">Drop or browse</span>}</label>; })}</div><div className="panel-footer"><span>Target resolution <strong>{active.resolution}px</strong></span><button className="primary" onClick={() => void runReferences()} disabled={!active.references.front || busy}>{activeStage?.status === "RUNNING" ? "Processing…" : "Process references"}</button></div></div>
            <div className="panel hardware"><div className="panel-header"><div><span className="eyebrow">SYSTEM</span><h3>Hardware profile</h3></div><span className="pill good">{hardware?.recommendation ?? "CHECKING"}</span></div>{gpu ? <div className="metric"><div className="metric-icon">▣</div><div><strong>{gpu.name}</strong><span>{(gpu.vram_mb / 1024).toFixed(1)} GB VRAM · driver {gpu.driver}</span></div></div> : <div className="metric"><div className="metric-icon">!</div><div><strong>NVIDIA GPU not detected</strong><span>Install a compatible driver to enable ML workers</span></div></div>}<div className="metric-row"><span>System RAM</span><strong>{hardware?.ram.total_gb ?? "—"} GB</strong></div><div className="metric-row"><span>Free disk</span><strong>{hardware?.disk.free_gb ?? "—"} GB</strong></div><div className="metric-row"><span>Blender</span><strong className={hardware?.blender.available ? "text-good" : "text-warning"}>{hardware?.blender.available ? "Available" : "Not installed"}</strong></div></div></div>
          <div className="panel stages"><div className="panel-header"><div><span className="eyebrow">PIPELINE</span><h3>Stages</h3></div><span className="muted">Single GPU queue</span></div><div className="stage-list">{["references", "geometry", "textures", "retopology", "rig", "motions", "export"].map((stage, index) => { const record = active.stages[stage]; const capability = capabilities?.stages[stage]; const canRun = capability?.available && (stage === "references" ? Boolean(active.references.front) : stage === "geometry" ? record?.status !== "RUNNING" && active.stages.references?.status === "READY" : stage === "textures" ? active.stages.geometry?.status === "READY" : stage === "retopology" ? active.stages.textures?.status === "READY" : stage === "rig" ? active.stages.retopology?.status === "READY" : stage === "export" ? active.stages.rig?.status === "READY" && active.export_actions.length > 0 : false); return <div className="stage-row" key={stage}><span className={`stage-number ${record?.status === "READY" ? "done" : ""}`}>{record?.status === "READY" ? "✓" : String(index + 1).padStart(2, "0")}</span><div className="stage-name"><strong>{stage}</strong><small>{record?.status ?? "PENDING"}{record?.error_message ? ` · ${record.error_message}` : capability?.reason ? ` · ${capability.reason}` : stage === "export" && !active.export_actions.length ? " · select actions before export" : ""}</small></div><span className={`stage-status ${record?.status === "READY" ? "ready" : record?.status === "FAILED" ? "failed" : ""}`}>{record?.status ?? "PENDING"}</span>{canRun && <button className="stage-action" onClick={() => void (stage === "references" ? runReferences() : runStage(stage))} disabled={busy || record?.status === "RUNNING"}>{record?.status === "RUNNING" ? "Running…" : "Run"}</button>}</div>; })}</div></div>
          <div className="tester-layout"><Viewport assetUrl={assetUrl} /><div className="panel inspector"><span className="eyebrow">UNIT TESTER</span><h3>Validation viewport</h3><p className="panel-note">The viewer loads only a GLB path from a READY validated stage. No model is present until a real geometry worker is installed.</p><div className="inspector-row"><span>Current job</span><strong>{active.job_id.slice(0, 8)}</strong></div><div className="inspector-row"><span>Reference stage</span><strong className={activeStage?.status === "READY" ? "text-good" : "text-warning"}>{activeStage?.status}</strong></div><div className="inspector-row"><span>Asset stage</span><strong className={assetUrl ? "text-good" : "text-warning"}>{assetStage?.name ?? "—"}</strong></div><button className="secondary wide" onClick={() => window.open(`/api/jobs/${active.job_id}/events`, "_blank")}>Open event stream</button></div></div>
        </>}</section></main>
  </div>;
}
export default App;
